// ============================================================
// CONVEX STUB — auto-generated by `npx convex dev`
//
// This file is a placeholder so TypeScript doesn't fail before
// the user has provisioned a Convex deployment. Once `npx convex dev`
// runs, it will overwrite this file with the real API surface
// generated from convex/schema.ts.
// ============================================================

/* eslint-disable @typescript-eslint/no-explicit-any */

export const api: any = new Proxy(
  {},
  {
    get(_target: any, prop: string) {
      return new Proxy(
        {},
        {
          get(_t2: any, prop2: string) {
            return `${prop}.${prop2}`;
          },
        }
      );
    },
  }
);

export const internal: any = api;
export const anyApi: any = api;
